# Build a Flutter app with Odevio

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      # Launch a build with Odevio
      bash script_cicd.sh $(ODEVIO_API_KEY_DEV) -t publication -m debug
    failOnStderr: true
    # workingDirectory: "$(System.DefaultWorkingDirectory)/projectFolder/"
    displayName: 'deploy-odevio-job'
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: odevio_ipa_url.txt
    displayName: 'Publish odevio_ipa_url Artifact'
