# Build an Flutter app with Odevio

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      # Install the zip command
      #sudo apt-get install zip
      # Launch a build with Odevio
      ./script_cicd.sh $(ODEVIO_API_KEY) -t 'ad-hoc'
    failOnStderr: true
    # workingDirectory: "$(System.DefaultWorkingDirectory)/projectFolder/"
    displayName: 'deploy-odevio-job'
